apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ob3f8h19j-java-quarkus
  janus-idp.io/tekton: ob3f8h19j-java-quarkus
  backstage.io/kubernetes-id: ob3f8h19j-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: ob3f8h19j-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
